# Helper script to copy Merlin.dll and Merlin.pdb
# Tries Debug first, falls back to Release if Debug doesn't exist

set(MERLIN_DLL_DEBUG "${DEBUG_DIR}/Merlin.dll")
set(MERLIN_PDB_DEBUG "${DEBUG_DIR}/Merlin.pdb")
set(MERLIN_DLL_RELEASE "${RELEASE_DIR}/Merlin.dll")
set(MERLIN_PDB_RELEASE "${RELEASE_DIR}/Merlin.pdb")

if(CONFIG STREQUAL "Debug")
    # In Debug config, prefer Debug build, fall back to Release
    if(EXISTS "${MERLIN_DLL_DEBUG}")
        message(STATUS "Copying Merlin.dll from Debug build")
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${MERLIN_DLL_DEBUG}" "${OUTPUT_DIR}/Merlin.dll")
        if(EXISTS "${MERLIN_PDB_DEBUG}")
            message(STATUS "Copying Merlin.pdb from Debug build")
            execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${MERLIN_PDB_DEBUG}" "${OUTPUT_DIR}/Merlin.pdb")
        endif()
    else()
        message(STATUS "Merlin Debug build not found, using Release build")
        if(EXISTS "${MERLIN_DLL_RELEASE}")
            execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${MERLIN_DLL_RELEASE}" "${OUTPUT_DIR}/Merlin.dll")
            if(EXISTS "${MERLIN_PDB_RELEASE}")
                execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${MERLIN_PDB_RELEASE}" "${OUTPUT_DIR}/Merlin.pdb")
            endif()
        else()
            message(WARNING "Merlin.dll not found in Debug or Release build directories!")
        endif()
    endif()
else()
    # In Release config, use Release build
    if(EXISTS "${MERLIN_DLL_RELEASE}")
        message(STATUS "Copying Merlin.dll from Release build")
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${MERLIN_DLL_RELEASE}" "${OUTPUT_DIR}/Merlin.dll")
        if(EXISTS "${MERLIN_PDB_RELEASE}")
            message(STATUS "Copying Merlin.pdb from Release build")
            execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${MERLIN_PDB_RELEASE}" "${OUTPUT_DIR}/Merlin.pdb")
        endif()
    else()
        message(WARNING "Merlin.dll not found in Release build directory!")
    endif()
endif()
